### ISSUE TITLE
Asset tests fail without "Should ISSUE new token" being run

### ISSUE THREAD

**Issue by xucito** [wavesplatform/waves-transactions#49]
As an assetId needs to be generated for tests such as "Should ReIssue Token", token generation should occur before all tests in assets.tests.ts

```js

    it('Should ISSUE new token', async () => {
      const txParams: IIssueParams = {
        name: 'Test token',
        description: 'no description',
        decimals: 3,
        quantity: 1000,
        chainId: CHAIN_ID,
        reissuable: true,
      }

      const tx = issue(txParams, account1)
      const resp = await broadcast(tx, API_BASE)
      expect(resp.type).toEqual(3)
      assetId = tx.id
      await waitForTx(assetId, { apiBase: API_BASE, timeout: TIMEOUT })
    }, TIMEOUT)
```

**Comment by siemarell** [comment]
I agree with you, and what you propose is good practice. But our tests take too long to execute because we need to wait for every transaction to be mined into a block. There are 3 options: 
1. Generate a token with 'before' hook. That way you wait an additional minute
2. Generate token and remove an explicit issue test. That way you lose an option to test issue params.
3. Make reissue test dependant on issue test. That way you cannot run reissue independently.
We chose 3. 
If you have a better option feel free to submit PR.
